services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"  # Replace 'bot.py' with the entry script of your bot
    envVars:
      - key: TOKEN
        value: ${TOKEN}
      - key: Waifu_Token
        value: ${Waifu_Token}
    branch: main
    repo: https://github.com/cringe-neko-girl/Waifu.it-Showcase.git
    pullRequestPreviews: false
    autoDeploy: true
    restartPolicy: always   # Ensures the service automatically restarts on failure but prevents double execution
