# render.yaml
services:
  - name: discord-bot
    type: web
    env: python
    plan: free # Adjust if you need a higher tier
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py" # Update 'main.py' to your bot's entry point
    envVars:
      - key: TOKEN
        value: "your_discord_bot_token_here" # Replace with your bot token
      - key: Waifu_Token
        value: "your_waifu_token_here" # Replace with your waifu token
